language: node_js
node_js:
  - "10"
cache: yarn
env:
  - NODE_ENV=production TIMESTAMP=$(date +%Y%m%d%H%M%S)
script:
  - yarn test
  - yarn build
  - mkdir -p artifacts && tar --exclude=artifacts --exclude=.git -zvcf artifacts/output-$TIMESTAMP.tar.gz .
addons:
  artifacts:
    paths:
    - artifacts/output-$TIMESTAMP.tar.gz
