language: node_js
node_js:
  - "10"
cache: yarn
addons:
  artifacts:
    paths:
    - $(git ls-files | tr "\n" ":")
    - $(find node_modules | tr "\n" ":")
    - $(find public | tr "\n" ":")
env:
  - NODE_ENV=production
script:
  - yarn test
  - yarn build