language: node_js
node_js:
  - "10"
script:
  - yarn test
  - NODE_ENV=production yarn build
  - NODE_ENV=production yarn install
  - mkdir -p artifacts && tar --exclude=artifacts --exclude=.git -zcf artifacts/output.tar.gz .
addons:
  artifacts:
    paths:
    - artifacts/output.tar.gz
